// frontend/src/app/pages/analysis/analysis.component.ts
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { LucideAngularModule, ArrowLeft, Award, FileText, CheckCircle, AlertTriangle, Lightbulb, BookOpen, Briefcase, Code, Star, Loader } from 'lucide-angular';

@Component({
  selector: 'app-analysis',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './analysis.component.html',
  styles: ``
})
export class AnalysisComponent implements OnInit {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private http = inject(HttpClient);

  // Icons
  ArrowLeft = ArrowLeft; Award = Award; FileText = FileText; CheckCircle = CheckCircle;
  AlertTriangle = AlertTriangle; Lightbulb = Lightbulb; BookOpen = BookOpen;
  Briefcase = Briefcase; Code = Code; Star = Star; Loader = Loader;

  id = '';
  activeTab = signal<'structure' | 'analysis'>('structure');
  jdText = signal('');
  
  resume = signal<any>(null);
  resumeLoading = signal(true);
  
  analyses = signal<any[]>([]);
  analyzeLoading = signal(false);
  analyzeError = signal('');

  parsed = computed(() => this.resume()?.parsed_structure || {});
  latestAnalysis = computed(() => this.analyses()[0]?.analysis_result || null);

  displaySkills = computed(() => {
    const s = this.parsed().skills || {};
    const list = [
      ...(s.all || []),
      ...(s.languages || []),
      ...(s.frameworks || []),
      ...(s.tools || []),
      ...(s.other || [])
    ].filter(Boolean);
    return [...new Set(list)];
  });

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      this.id = params.get('id') || '';
      if (this.id) {
        this.fetchData();
      }
    });
  }

  fetchData() {
    this.resumeLoading.set(true);
    
    this.http.get<any>(`http://localhost:8081/api/v1/resumes/${this.id}`).subscribe({
      next: (data) => {
        this.resume.set(data);
        this.resumeLoading.set(false);
      },
      error: () => this.resumeLoading.set(false)
    });

    this.fetchAnalyses();
  }

  fetchAnalyses() {
    this.http.get<any[]>(`http://localhost:8081/api/v1/analysis/${this.id}`).subscribe({
      next: (data) => this.analyses.set(data),
      error: () => {}
    });
  }

  runAnalysis() {
    this.analyzeLoading.set(true);
    this.analyzeError.set('');

    this.http.post<any>('http://localhost:8081/api/v1/analysis/analyze', {
      resume_id: this.id,
      jd_text: this.jdText()
    }).subscribe({
      next: () => {
        this.fetchAnalyses();
        this.activeTab.set('analysis');
        this.analyzeLoading.set(false);
      },
      error: (err) => {
        this.analyzeError.set(err.error?.error || 'Failed to analyze resume');
        this.analyzeLoading.set(false);
      }
    });
  }

  goBack() {
    this.router.navigate(['/dashboard']);
  }
}

<div class="min-h-screen bg-transparent pb-12">
  <div class="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
    <div class="w-full flex items-center gap-4">
      <button 
        (click)="goBack()" 
        class="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
      >
        <lucide-icon [img]="ArrowLeft" [size]="20"></lucide-icon>
      </button>
      <div class="flex-1">
        <h1 class="text-2xl font-extrabold tracking-tight truncate max-w-[300px] md:max-w-none text-white">
          {{ resume()?.filename || 'Resume Analysis' }}
        </h1>
        <p class="text-purple-200 text-sm mt-0.5">
          <ng-container *ngIf="resume()">Uploaded on {{ resume()?.uploaded_at | date }}</ng-container>
          <ng-container *ngIf="!resume()">Loading...</ng-container>
        </p>
      </div>
    </div>
  </div>

  <div class="max-w-4xl mx-auto px-4 mt-28">
    <div class="flex bg-white/60 p-1.5 rounded-xl mb-6 max-w-md mx-auto border border-white/85">
      <button
        (click)="activeTab.set('structure')"
        [class]="'flex-1 py-3 text-sm font-semibold rounded-2xl transition-all cursor-pointer ' + 
          (activeTab() === 'structure' ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-primary-600 shadow-sm' : 'text-gray-500 hover:text-gray-700 dark:text-gray-300')"
      >
        Parsed Structure
      </button>
      <button
        (click)="activeTab.set('analysis')"
        [class]="'flex-1 py-3 text-sm font-semibold rounded-2xl transition-all cursor-pointer ' + 
          (activeTab() === 'analysis' ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-primary-600 shadow-sm' : 'text-gray-500 hover:text-gray-700 dark:text-gray-300')"
      >
        AI Review & ATS
      </button>
    </div>

    <div *ngIf="resumeLoading()" class="text-center py-12 text-gray-500">Loading resume...</div>

    <div *ngIf="!resumeLoading()">
      <!-- TAB 1: Structure -->
      <div *ngIf="activeTab() === 'structure'" class="space-y-6">
        
        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h3 class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
            <lucide-icon [img]="Star" class="text-primary-500" [size]="20"></lucide-icon> Personal Information
          </h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div><span class="text-gray-400">Name:</span> <span class="font-semibold text-gray-700 dark:text-gray-300">{{ parsed().personal?.name }}</span></div>
            <div><span class="text-gray-400">Email:</span> <span class="font-semibold text-gray-700 dark:text-gray-300">{{ parsed().personal?.email }}</span></div>
            <div><span class="text-gray-400">Phone:</span> <span class="font-semibold text-gray-700 dark:text-gray-300">{{ parsed().personal?.phone }}</span></div>
            <div><span class="text-gray-400">Location:</span> <span class="font-semibold text-gray-700 dark:text-gray-300">{{ parsed().personal?.location }}</span></div>
          </div>
        </div>

        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h3 class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
            <lucide-icon [img]="BookOpen" class="text-primary-500" [size]="20"></lucide-icon> Education
          </h3>
          <div *ngIf="parsed().education?.length > 0; else noEdu" class="space-y-4">
            <div *ngFor="let edu of parsed().education" class="border-l-2 border-primary-200 pl-4 py-1">
              <h4 class="font-bold text-gray-800 dark:text-gray-200">{{ edu.degree }} <span *ngIf="edu.field">in {{ edu.field }}</span></h4>
              <p class="text-gray-600 text-sm">{{ edu.institution }} <span *ngIf="edu.year_end">• Class of {{ edu.year_end }}</span></p>
              <p *ngIf="edu.cgpa" class="text-primary-500 text-xs font-semibold mt-1">Score: {{ edu.cgpa }}</p>
            </div>
          </div>
          <ng-template #noEdu><p class="text-gray-400 text-sm">No education data found</p></ng-template>
        </div>

        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h3 class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
            <lucide-icon [img]="Briefcase" class="text-primary-500" [size]="20"></lucide-icon> Work Experience
          </h3>
          <div *ngIf="parsed().experience?.length > 0; else noExp" class="space-y-6">
            <div *ngFor="let exp of parsed().experience" class="border-l-2 border-primary-200 pl-4">
              <div class="flex justify-between items-start flex-wrap gap-1">
                <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg">{{ exp.title }}</h4>
                <span class="text-xs bg-primary-50 text-primary-600 px-3 py-1 rounded-full border border-primary-100 font-semibold">
                  {{ exp.duration_start }} <span *ngIf="exp.duration_end">to {{ exp.duration_end }}</span>
                </span>
              </div>
              <p class="text-gray-600 text-sm font-semibold">{{ exp.company }}</p>
              
              <div *ngIf="exp.keywords?.length > 0; else noKeywords" class="flex flex-wrap gap-1.5 mt-2">
                <span *ngFor="let kw of exp.keywords" class="text-xs bg-gray-100 text-gray-600 px-2.5 py-1 rounded-xl border border-gray-200">{{ kw }}</span>
              </div>
              <ng-template #noKeywords>
                <p class="text-gray-500 text-sm mt-2 line-clamp-3">{{ exp.description }}</p>
              </ng-template>
            </div>
          </div>
          <ng-template #noExp><p class="text-gray-400 text-sm">No work experience found</p></ng-template>
        </div>

        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h3 class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
            <lucide-icon [img]="Code" class="text-primary-500" [size]="20"></lucide-icon> Skills
          </h3>
          
          <div *ngIf="displaySkills().length > 0 || (parsed().skills?.experience_keywords?.length > 0); else noSkills">
            <div *ngIf="displaySkills().length > 0" class="space-y-4">
              <div class="flex flex-wrap gap-2">
                <span *ngFor="let skill of displaySkills()" class="bg-white dark:bg-[#100818] dark:text-gray-100 px-4 py-2 rounded-2xl shadow-sm text-sm font-semibold text-gray-700 dark:text-gray-300 border border-primary-100">
                  {{ skill }}
                </span>
              </div>
              
              <div *ngIf="parsed().skills?.experience_keywords?.length > 0">
                <p class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Keywords from Experience</p>
                <div class="flex flex-wrap gap-1.5">
                  <span *ngFor="let kw of parsed().skills.experience_keywords.slice(0, 25)" class="text-xs bg-blue-50 text-blue-600 px-2.5 py-1 rounded-xl border border-blue-100">{{ kw }}</span>
                </div>
              </div>

              <div *ngIf="parsed().skills?.project_keywords?.length > 0">
                <p class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Keywords from Projects</p>
                <div class="flex flex-wrap gap-1.5">
                  <span *ngFor="let kw of parsed().skills.project_keywords.slice(0, 20)" class="text-xs bg-emerald-50 text-emerald-600 px-2.5 py-1 rounded-xl border border-emerald-100">{{ kw }}</span>
                </div>
              </div>
            </div>
          </div>
          <ng-template #noSkills>
            <p class="text-gray-400 text-sm">No skills extracted. Try running the AI Review to identify key skills from your experience.</p>
          </ng-template>
        </div>
      </div>

      <!-- TAB 2: Analysis -->
      <div *ngIf="activeTab() === 'analysis'" class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        <div class="lg:col-span-1 space-y-6">
          <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60 h-full">
            <h3 class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-2">Target Job Description</h3>
            <p class="text-gray-400 text-sm mb-4">Paste the Job Description below to evaluate match and extract missing keywords.</p>
            
            <textarea
              rows="12"
              [ngModel]="jdText()"
              (ngModelChange)="jdText.set($event)"
              placeholder="Paste the Job Description / Job Ad here..."
              class="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-gray-700 dark:text-gray-300 text-sm mb-4 resize-none"
            ></textarea>

            <button
              (click)="runAnalysis()"
              [disabled]="analyzeLoading()"
              class="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive"
            >
              <ng-container *ngIf="analyzeLoading(); else analyzeBtn">
                <lucide-icon [img]="Loader" class="animate-spin" [size]="18"></lucide-icon> Analyzing...
              </ng-container>
              <ng-template #analyzeBtn>Analyze</ng-template>
            </button>
            <div *ngIf="analyzeError()" class="mt-4 p-3 bg-red-50 text-red-600 rounded-2xl text-sm border border-red-100 text-center">
              {{ analyzeError() }}
            </div>
          </div>
        </div>

        <div class="lg:col-span-2 space-y-6">
          <div *ngIf="latestAnalysis(); else noAnalysis">
            
            <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60 flex flex-col md:flex-row items-center gap-6 mb-6">
              <div class="w-28 h-28 rounded-full gradient-header text-white flex flex-col items-center justify-center shadow-lg shrink-0">
                <span class="text-4xl font-black">{{ latestAnalysis().overall_rating || 0 }}</span>
                <span class="text-xs font-semibold text-white/80">/10 Rating</span>
              </div>
              <div>
                <h3 class="text-2xl font-bold text-gray-800 dark:text-gray-200">Overall Assessment</h3>
                <p class="text-gray-600 text-sm mt-1 leading-relaxed">{{ latestAnalysis().summary }}</p>
                
                <div *ngIf="analyses()[0]?.ats_score !== null" class="mt-4 flex items-center gap-3">
                  <span class="text-sm font-bold text-emerald-600 bg-emerald-50 px-3 py-1.5 rounded-2xl border border-emerald-200 flex items-center gap-1.5">
                    <lucide-icon [img]="Award" [size]="16"></lucide-icon> ATS Match: {{ analyses()[0].ats_score }}%
                  </span>
                </div>
              </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                  <lucide-icon [img]="CheckCircle" class="text-emerald-500" [size]="20"></lucide-icon> Strengths
                </h4>
                <ul class="space-y-2 text-sm text-gray-600 pl-1">
                  <li *ngFor="let str of latestAnalysis().strengths" class="flex gap-2">
                    <span class="text-emerald-500 font-bold">•</span>
                    <span>{{ str }}</span>
                  </li>
                </ul>
              </div>

              <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                  <lucide-icon [img]="AlertTriangle" class="text-amber-500" [size]="20"></lucide-icon> Areas to Improve
                </h4>
                <ul class="space-y-2 text-sm text-gray-600 pl-1">
                  <li *ngFor="let weak of latestAnalysis().weaknesses" class="flex gap-2">
                    <span class="text-amber-500 font-bold">•</span>
                    <span>{{ weak }}</span>
                  </li>
                </ul>
              </div>

              <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60 md:col-span-2">
                <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                  <lucide-icon [img]="Lightbulb" class="text-primary-500" [size]="20"></lucide-icon> Specific Suggestions
                </h4>
                <div class="space-y-3">
                  <div *ngFor="let sug of latestAnalysis().suggestions" class="bg-white dark:bg-[#100818] dark:text-gray-100 p-4 rounded-2xl border border-primary-50/50 shadow-sm flex items-start gap-3">
                    <span class="text-xs font-bold text-primary-600 bg-primary-50 px-2.5 py-1 rounded-full uppercase border border-primary-100 mt-0.5 shrink-0">
                      {{ sug.section }}
                    </span>
                    <p class="text-sm text-gray-600 mt-0.5">{{ sug.suggestion }}</p>
                  </div>
                </div>
              </div>

              <div *ngIf="latestAnalysis().ats_keywords_missing?.length > 0" class="glass-card rounded-2xl p-6 shadow-sm border border-white/60 md:col-span-2">
                <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4">Missing ATS Keywords</h4>
                <div class="flex flex-wrap gap-2">
                  <span *ngFor="let kw of latestAnalysis().ats_keywords_missing" class="bg-amber-50 text-amber-700 px-3 py-1.5 rounded-2xl text-xs font-semibold border border-amber-200">
                    {{ kw }}
                  </span>
                </div>
              </div>
            </div>
          </div>
          
          <ng-template #noAnalysis>
            <div class="bg-white/50 border border-dashed border-gray-200 rounded-xl p-8 text-center text-gray-500 h-full flex flex-col items-center justify-center min-h-[300px]">
              <lucide-icon [img]="FileText" class="text-gray-300 mb-3" [size]="48"></lucide-icon>
              <p>Paste a Job Description on the left and click <b>Analyze</b> <br/> to get an AI assessment.</p>
            </div>
          </ng-template>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/Analysis.jsx
import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../api/axios';
import { ArrowLeft, Award, FileText, CheckCircle, AlertTriangle, Lightbulb, BookOpen, Briefcase, Code, Star, Loader } from 'lucide-react';

export default function Analysis() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [jdText, setJdText] = useState('');
  const [activeTab, setActiveTab] = useState('structure'); // 'structure' or 'analysis'

  // Fetch Resume details
  const { data: resume, isLoading: resumeLoading } = useQuery({
    queryKey: ['resume', id],
    queryFn: async () => {
      const res = await api.get(`/resumes/${id}`);
      return res.data;
    }
  });

  // Fetch past analyses
  const { data: analyses = [], isLoading: analysesLoading } = useQuery({
    queryKey: ['analyses', id],
    queryFn: async () => {
      const res = await api.get(`/analysis/${id}`);
      return res.data;
    }
  });

  // Run analysis mutation
  const analyzeMutation = useMutation({
    mutationFn: async () => {
      const res = await api.post('/analysis/analyze', {
        resume_id: id,
        jd_text: jdText
      });
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries(['analyses', id]);
      setActiveTab('analysis');
    }
  });

  const latestAnalysis = analyses[0]?.analysis_result || null;
  const parsed = resume?.parsed_structure || {};

  return (
    <div className="min-h-screen bg-transparent pb-12">
      {/* Header (Static/Unscrollable) */}
      <div className="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
        <div className="w-full flex items-center gap-4">
          <button 
            onClick={() => navigate('/dashboard')} 
            className="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
          >
            <ArrowLeft size={20} />
          </button>
          <div className="flex-1">
            <h1 className="text-2xl font-extrabold tracking-tight truncate max-w-[300px] md:max-w-none text-white">
              {resume?.filename || 'Resume Analysis'}
            </h1>
            <p className="text-purple-200 text-sm mt-0.5">
              {resume ? `Uploaded on ${new Date(resume.uploaded_at).toLocaleDateString()}` : 'Loading...'}
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 mt-28">
        {/* Toggle tabs */}
        <div className="flex bg-white/60 p-1.5 rounded-xl mb-6 max-w-md mx-auto border border-white/85">
          <button
            onClick={() => setActiveTab('structure')}
            className={`flex-1 py-3 text-sm font-semibold rounded-2xl transition-all cursor-pointer ${
              activeTab === 'structure' 
                ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-primary-600 shadow-sm' 
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-300'
            }`}
          >
            Parsed Structure
          </button>
          <button
            onClick={() => setActiveTab('analysis')}
            className={`flex-1 py-3 text-sm font-semibold rounded-2xl transition-all cursor-pointer ${
              activeTab === 'analysis' 
                ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-primary-600 shadow-sm' 
                : 'text-gray-500 hover:text-gray-700 dark:text-gray-300'
            }`}
          >
            AI Review & ATS
          </button>
        </div>

        {resumeLoading ? (
          <div className="text-center py-12 text-gray-500">Loading resume...</div>
        ) : (
          <div>
            {/* TAB 1: Structure */}
            {activeTab === 'structure' && (
              <div className="space-y-6">
                {/* Personal Info */}
                <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
                    <Star className="text-primary-500" size={20} /> Personal Information
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div><span className="text-gray-400">Name:</span> <span className="font-semibold text-gray-700 dark:text-gray-300">{parsed.personal?.name}</span></div>
                    <div><span className="text-gray-400">Email:</span> <span className="font-semibold text-gray-700 dark:text-gray-300">{parsed.personal?.email}</span></div>
                    <div><span className="text-gray-400">Phone:</span> <span className="font-semibold text-gray-700 dark:text-gray-300">{parsed.personal?.phone}</span></div>
                    <div><span className="text-gray-400">Location:</span> <span className="font-semibold text-gray-700 dark:text-gray-300">{parsed.personal?.location}</span></div>
                  </div>
                </div>

                {/* Education */}
                <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
                    <BookOpen className="text-primary-500" size={20} /> Education
                  </h3>
                  {parsed.education?.length > 0 ? (
                    <div className="space-y-4">
                      {parsed.education.map((edu, idx) => (
                        <div key={idx} className="border-l-2 border-primary-200 pl-4 py-1">
                          <h4 className="font-bold text-gray-800 dark:text-gray-200">{edu.degree} {edu.field && `in ${edu.field}`}</h4>
                          <p className="text-gray-600 text-sm">{edu.institution} {edu.year_end && `• Class of ${edu.year_end}`}</p>
                          {edu.cgpa && <p className="text-primary-500 text-xs font-semibold mt-1">Score: {edu.cgpa}</p>}
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-gray-400 text-sm">No education data found</p>
                  )}
                </div>

                {/* Experience */}
                <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
                    <Briefcase className="text-primary-500" size={20} /> Work Experience
                  </h3>
                  {parsed.experience?.length > 0 ? (
                    <div className="space-y-6">
                      {parsed.experience.map((exp, idx) => (
                        <div key={idx} className="border-l-2 border-primary-200 pl-4">
                          <div className="flex justify-between items-start flex-wrap gap-1">
                            <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg">{exp.title}</h4>
                            <span className="text-xs bg-primary-50 text-primary-600 px-3 py-1 rounded-full border border-primary-100 font-semibold">
                              {exp.duration_start} {exp.duration_end && `to ${exp.duration_end}`}
                            </span>
                          </div>
                          <p className="text-gray-600 text-sm font-semibold">{exp.company}</p>
                          {/* Show extracted keywords if available, else fall back to description */}
                          {exp.keywords?.length > 0 ? (
                            <div className="flex flex-wrap gap-1.5 mt-2">
                              {exp.keywords.map((kw, ki) => (
                                <span key={ki} className="text-xs bg-gray-100 text-gray-600 px-2.5 py-1 rounded-xl border border-gray-200">{kw}</span>
                              ))}
                            </div>
                          ) : (
                            <p className="text-gray-500 text-sm mt-2 line-clamp-3">{exp.description}</p>
                          )}
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-gray-400 text-sm">No work experience found</p>
                  )}
                </div>

                {/* Skills */}
                <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 flex items-center gap-2">
                    <Code className="text-primary-500" size={20} /> Skills
                  </h3>
                  {(() => {
                    const s = parsed.skills || {};
                    // Use the 'all' deduplicated list, fallback to languages, fallback to experience_keywords
                    const displaySkills = [
                      ...(s.all || []),
                      ...(s.languages || []),
                      ...(s.frameworks || []),
                      ...(s.tools || []),
                      ...(s.other || [])
                    ].filter(Boolean);
                    const uniqueSkills = [...new Set(displaySkills)];
                    const expKw = s.experience_keywords || [];
                    const projKw = s.project_keywords || [];
                    return uniqueSkills.length > 0 ? (
                      <div className="space-y-4">
                        <div className="flex flex-wrap gap-2">
                          {uniqueSkills.map((skill, idx) => (
                            <span key={idx} className="bg-white dark:bg-[#100818] dark:text-gray-100 px-4 py-2 rounded-2xl shadow-sm text-sm font-semibold text-gray-700 dark:text-gray-300 border border-primary-100">
                              {skill}
                            </span>
                          ))}
                        </div>
                        {expKw.length > 0 && (
                          <div>
                            <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Keywords from Experience</p>
                            <div className="flex flex-wrap gap-1.5">
                              {expKw.slice(0, 25).map((kw, idx) => (
                                <span key={idx} className="text-xs bg-blue-50 text-blue-600 px-2.5 py-1 rounded-xl border border-blue-100">{kw}</span>
                              ))}
                            </div>
                          </div>
                        )}
                        {projKw.length > 0 && (
                          <div>
                            <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Keywords from Projects</p>
                            <div className="flex flex-wrap gap-1.5">
                              {projKw.slice(0, 20).map((kw, idx) => (
                                <span key={idx} className="text-xs bg-emerald-50 text-emerald-600 px-2.5 py-1 rounded-xl border border-emerald-100">{kw}</span>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    ) : expKw.length > 0 ? (
                      <div>
                        <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Keywords Extracted from Experience</p>
                        <div className="flex flex-wrap gap-1.5">
                          {expKw.slice(0, 30).map((kw, idx) => (
                            <span key={idx} className="text-xs bg-blue-50 text-blue-600 px-2.5 py-1 rounded-xl border border-blue-100">{kw}</span>
                          ))}
                        </div>
                      </div>
                    ) : (
                      <p className="text-gray-400 text-sm">No skills extracted. Try running the AI Review to identify key skills from your experience.</p>
                    );
                  })()}
                </div>
              </div>
            )}

            {/* TAB 2: Analysis */}
            {activeTab === 'analysis' && (
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                
                {/* Left Column: Input */}
                <div className="lg:col-span-1 space-y-6">
                  <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60 h-full">
                    <h3 className="text-xl font-bold text-gray-800 dark:text-gray-200 mb-2">Target Job Description</h3>
                    <p className="text-gray-400 text-sm mb-4">Paste the Job Description below to evaluate match and extract missing keywords.</p>
                    
                    <textarea
                      rows={12}
                      value={jdText}
                      onChange={(e) => setJdText(e.target.value)}
                      placeholder="Paste the Job Description / Job Ad here..."
                      className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-gray-700 dark:text-gray-300 text-sm mb-4 resize-none"
                    />

                    <button
                      onClick={() => analyzeMutation.mutate()}
                      disabled={analyzeMutation.isPending}
                      className="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive"
                    >
                      {analyzeMutation.isPending ? (
                        <>
                          <Loader className="animate-spin" size={18} />
                          Analyzing...
                        </>
                      ) : (
                        'Analyze'
                      )}
                    </button>
                    {analyzeMutation.isError && (
                      <div className="mt-4 p-3 bg-red-50 text-red-600 rounded-2xl text-sm border border-red-100 text-center">
                        {analyzeMutation.error?.response?.data?.error || 'Failed to analyze resume'}
                      </div>
                    )}
                  </div>
                </div>

                {/* Right Column: Output */}
                <div className="lg:col-span-2 space-y-6">
                  {latestAnalysis ? (
                    <>
                      {/* Score Section */}
                      <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60 flex flex-col md:flex-row items-center gap-6">
                        <div className="w-28 h-28 rounded-full gradient-header text-white flex flex-col items-center justify-center shadow-lg shrink-0">
                          <span className="text-4xl font-black">{latestAnalysis.overall_rating || 0}</span>
                          <span className="text-xs font-semibold text-white/80">/10 Rating</span>
                        </div>
                        <div>
                          <h3 className="text-2xl font-bold text-gray-800 dark:text-gray-200">Overall Assessment</h3>
                          <p className="text-gray-600 text-sm mt-1 leading-relaxed">{latestAnalysis.summary}</p>
                          
                          {/* ATS Score display if available */}
                          {analyses[0]?.ats_score !== null && (
                            <div className="mt-4 flex items-center gap-3">
                              <span className="text-sm font-bold text-emerald-600 bg-emerald-50 px-3 py-1.5 rounded-2xl border border-emerald-200 flex items-center gap-1.5">
                                <Award size={16} /> ATS Match: {analyses[0].ats_score}%
                              </span>
                            </div>
                          )}
                        </div>
                      </div>

                      {/* Main feedback content */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Strengths & Weaknesses */}
                        <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                          <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                            <CheckCircle className="text-emerald-500" size={20} /> Strengths
                          </h4>
                          <ul className="space-y-2 text-sm text-gray-600 pl-1">
                            {latestAnalysis.strengths?.map((str, idx) => (
                              <li key={idx} className="flex gap-2">
                                <span className="text-emerald-500 font-bold">•</span>
                                <span>{str}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                          <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                            <AlertTriangle className="text-amber-500" size={20} /> Areas to Improve
                          </h4>
                          <ul className="space-y-2 text-sm text-gray-600 pl-1">
                            {latestAnalysis.weaknesses?.map((weak, idx) => (
                              <li key={idx} className="flex gap-2">
                                <span className="text-amber-500 font-bold">•</span>
                                <span>{weak}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Suggestions */}
                        <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60 md:col-span-2">
                          <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4 flex items-center gap-2">
                            <Lightbulb className="text-primary-500" size={20} /> Specific Suggestions
                          </h4>
                          <div className="space-y-3">
                            {latestAnalysis.suggestions?.map((sug, idx) => (
                              <div key={idx} className="bg-white dark:bg-[#100818] dark:text-gray-100 p-4 rounded-2xl border border-primary-50/50 shadow-sm flex items-start gap-3">
                                <span className="text-xs font-bold text-primary-600 bg-primary-50 px-2.5 py-1 rounded-full uppercase border border-primary-100 mt-0.5 shrink-0">
                                  {sug.section}
                                </span>
                                <p className="text-sm text-gray-600 mt-0.5">{sug.suggestion}</p>
                              </div>
                            ))}
                          </div>
                        </div>

                        {/* Missing Keywords */}
                        {latestAnalysis.ats_keywords_missing?.length > 0 && (
                          <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60 md:col-span-2">
                            <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-4">Missing ATS Keywords</h4>
                            <div className="flex flex-wrap gap-2">
                              {latestAnalysis.ats_keywords_missing.map((kw, idx) => (
                                <span key={idx} className="bg-amber-50 text-amber-700 px-3 py-1.5 rounded-2xl text-xs font-semibold border border-amber-200">
                                  {kw}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    </>
                  ) : (
                    <div className="bg-white/50 border border-dashed border-gray-200 rounded-xl p-8 text-center text-gray-500 h-full flex flex-col items-center justify-center min-h-[300px]">
                      <FileText className="text-gray-300 mb-3" size={48} />
                      <p>Paste a Job Description on the left and click <b>Analyze</b> <br/> to get an AI assessment.</p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
