// frontend/src/app/pages/interview/interview.component.ts
import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { LucideAngularModule, ArrowLeft, Mic, MicOff, Send, CheckCircle, AlertTriangle, Play, Award, Loader, ChevronRight, Volume2, Target } from 'lucide-angular';

@Component({
  selector: 'app-interview',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './interview.component.html',
  styles: ``
})
export class InterviewComponent implements OnInit, OnDestroy {
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private http = inject(HttpClient);

  // Icons
  ArrowLeft = ArrowLeft; Mic = Mic; MicOff = MicOff; Send = Send; CheckCircle = CheckCircle;
  AlertTriangle = AlertTriangle; Play = Play; Award = Award; Loader = Loader;
  ChevronRight = ChevronRight; Volume2 = Volume2; Target = Target;

  id = '';
  sessionIdParam = '';

  interviewHistory = signal<any[]>([]);

  sessionStarted = signal(false);
  sessionEnded = signal(false);
  sessionId = signal<string | null>(null);
  sessionType = signal('behavioral');

  questionNumber = signal(1);
  currentQuestion = signal('');
  userAnswer = signal('');

  loadingQuestion = signal(false);
  loadingFeedback = signal(false);

  feedback = signal<any>(null);
  sessionDetails = signal<any>(null);

  isListening = signal(false);
  recognition: any = null;

  ngOnInit() {
    this.route.paramMap.subscribe(params => {
      this.id = params.get('id') || '';
    });
    this.route.queryParamMap.subscribe(queryParams => {
      this.sessionIdParam = queryParams.get('session') || '';
      if (this.sessionIdParam) {
        this.fetchSessionDetails(this.sessionIdParam);
      }
    });

    this.fetchHistory();
    this.initSpeechRecognition();
  }

  ngOnDestroy() {
    if (this.recognition && this.isListening()) {
      this.recognition.stop();
    }
  }

  initSpeechRecognition() {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SpeechRecognition) {
      this.recognition = new SpeechRecognition();
      this.recognition.continuous = true;
      this.recognition.interimResults = true;
      this.recognition.lang = 'en-US';

      this.recognition.onresult = (event: any) => {
        let finalTranscript = '';
        for (let i = event.resultIndex; i < event.results.length; ++i) {
          if (event.results[i].isFinal) {
            finalTranscript += event.results[i][0].transcript;
          }
        }
        if (finalTranscript) {
          this.userAnswer.update(v => v + (v ? ' ' : '') + finalTranscript);
        }
      };

      this.recognition.onerror = (e: any) => {
        console.error('Speech recognition error:', e);
        this.isListening.set(false);
      };

      this.recognition.onend = () => {
        this.isListening.set(false);
      };
    }
  }

  fetchHistory() {
    this.http.get<any[]>('http://localhost:8081/api/v1/interview/sessions').subscribe({
      next: (data) => this.interviewHistory.set(data),
      error: () => {}
    });
  }

  fetchSessionDetails(sid: string) {
    this.http.get<any>(`http://localhost:8081/api/v1/interviews/${sid}`).subscribe({
      next: (data) => {
        this.sessionDetails.set(data);
        this.sessionEnded.set(true);
        this.sessionStarted.set(true);
      },
      error: (e) => console.error(e)
    });
  }

  toggleListening() {
    if (!this.recognition) {
      alert('Speech Recognition is not supported in this browser.');
      return;
    }
    if (this.isListening()) {
      this.recognition.stop();
      this.isListening.set(false);
    } else {
      this.recognition.start();
      this.isListening.set(true);
    }
  }

  handleStartSession() {
    this.loadingQuestion.set(true);
    this.http.post<any>('http://localhost:8081/api/v1/interviews/start', {
      resume_id: this.id,
      session_type: this.sessionType()
    }).subscribe({
      next: (res) => {
        this.sessionId.set(res.session_id);
        this.currentQuestion.set(res.first_question);
        this.sessionStarted.set(true);
        this.questionNumber.set(1);
        this.loadingQuestion.set(false);
      },
      error: (e) => {
        console.error(e);
        alert('Failed to start interview.');
        this.loadingQuestion.set(false);
      }
    });
  }

  handleSubmitAnswer() {
    if (!this.userAnswer().trim()) return;
    this.loadingFeedback.set(true);
    this.http.post<any>(`http://localhost:8081/api/v1/interviews/${this.sessionId()}/answer`, {
      question_number: this.questionNumber(),
      question_text: this.currentQuestion(),
      answer: this.userAnswer()
    }).subscribe({
      next: (res) => {
        this.feedback.set(res.feedback);
        if (this.recognition && this.isListening()) {
          this.recognition.stop();
        }
        this.loadingFeedback.set(false);
      },
      error: (e) => {
        console.error(e);
        alert('Failed to submit answer.');
        this.loadingFeedback.set(false);
      }
    });
  }

  handleNextQuestion() {
    const fb = this.feedback();
    if (!fb) return;
    this.currentQuestion.set(fb.follow_up_question || 'No more questions. Click End Session.');
    this.userAnswer.set('');
    this.feedback.set(null);
    this.questionNumber.update(v => v + 1);
  }

  handleEndSession() {
    this.loadingQuestion.set(true);
    this.http.post<any>(`http://localhost:8081/api/v1/interviews/${this.sessionId()}/end`, {}).subscribe({
      next: () => {
        if (this.sessionId()) this.fetchSessionDetails(this.sessionId()!);
        this.loadingQuestion.set(false);
      },
      error: (e) => {
        console.error(e);
        alert('Failed to end session.');
        this.loadingQuestion.set(false);
      }
    });
  }

  handleSpeakQuestion() {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(this.currentQuestion());
      utterance.rate = 0.95;
      window.speechSynthesis.speak(utterance);
    }
  }

  reloadWithSession(resumeId: string, sid: string) {
    window.location.href = `/interview/${resumeId}?session=${sid}`;
  }

  goBack() {
    this.router.navigate(['/dashboard']);
  }
}

<div class="min-h-screen bg-transparent pb-12">
  <div class="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
    <div class="w-full flex items-center gap-4">
      <button 
        (click)="goBack()" 
        class="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
      >
        <lucide-icon [img]="ArrowLeft" [size]="20"></lucide-icon>
      </button>
      <div>
        <h1 class="text-2xl font-extrabold tracking-tight text-white">AI Mock Coach</h1>
        <p class="text-purple-200 text-sm mt-0.5">Real-time mock interview grounded in your resume</p>
      </div>
    </div>
  </div>

  <div class="max-w-3xl mx-auto px-4 mt-28">
    
    <!-- PHASE 1: START SCREEN -->
    <div *ngIf="!sessionStarted()" class="space-y-6">
      <div class="glass-card rounded-2xl p-8 shadow-md border border-white/60 text-center">
        <div class="w-20 h-20 bg-purple-100 dark:bg-purple-900/40 text-purple-600 dark:text-purple-400 rounded-xl mx-auto flex items-center justify-center mb-6 shadow-sm">
          <lucide-icon [img]="Play" [size]="36" class="fill-current"></lucide-icon>
        </div>
        
        <h2 class="text-2xl font-extrabold text-gray-800 dark:text-gray-200 tracking-tight">Ready to Prep?</h2>
        <p class="text-gray-500 text-sm max-w-sm mx-auto mt-2 leading-relaxed">
          We'll generate customized questions targeting the experience and projects on your resume.
        </p>

        <div class="mt-8 max-w-xs mx-auto space-y-4">
          <div class="text-left">
            <label class="text-xs font-bold text-gray-400 uppercase tracking-wider block mb-2 pl-2">
              Choose session type
            </label>
            <div class="flex bg-gray-100/50 p-1 rounded-2xl border border-gray-100">
              <button
                *ngFor="let type of ['behavioral', 'technical', 'management']"
                (click)="sessionType.set(type)"
                [class]="'flex-1 py-2 text-xs font-bold rounded-xl uppercase transition-all cursor-pointer ' + 
                  (sessionType() === type ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-purple-600 dark:text-purple-400 shadow-sm' : 'text-gray-400 hover:text-gray-500')"
              >
                {{ type }}
              </button>
            </div>
          </div>

          <button
            (click)="handleStartSession()"
            [disabled]="loadingQuestion()"
            class="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive cursor-pointer"
          >
            {{ loadingQuestion() ? 'Generating first question...' : 'Start Interview' }}
          </button>
        </div>
      </div>

      <div class="space-y-4">
        <h3 class="text-lg font-bold text-white tracking-tight pl-1">Past Sessions History</h3>
        <div class="space-y-3">
          <div *ngIf="interviewHistory().length === 0" class="bg-white/5 border border-dashed border-white/10 rounded-2xl p-8 text-center text-white/60 text-sm">
            No mock sessions completed yet.
          </div>
          
          <div *ngFor="let session of interviewHistory()" (click)="reloadWithSession(session.resume_id, session.id)" class="glass-card rounded-xl p-4 shadow-sm hover:shadow-lg transition-all border border-white/40 flex items-center justify-between cursor-pointer group">
            <div class="flex items-center gap-3 min-w-0">
              <div class="p-3 bg-purple-50 dark:bg-purple-900/20 text-purple-650 rounded-2xl shrink-0">
                <lucide-icon [img]="Target" [size]="18"></lucide-icon>
              </div>
              <div class="min-w-0">
                <h4 class="font-bold text-slate-800 dark:text-slate-200 group-hover:text-purple-600 dark:text-purple-400 transition-colors capitalize truncate max-w-[180px] sm:max-w-[240px]">
                  {{ session.session_type }} Prep
                </h4>
                <p class="text-slate-400 text-[10px] mt-0.5">
                  {{ session.started_at | date }} • {{ session.question_count }} Qs
                </p>
              </div>
            </div>
            <div class="flex items-center gap-1.5 shrink-0">
              <span class="font-black text-slate-700 bg-slate-100 px-2.5 py-0.5 rounded-full text-[10px]">
                {{ session.overall_score || 0 }}%
              </span>
              <lucide-icon [img]="ChevronRight" [size]="14" class="text-slate-400 group-hover:text-purple-600 dark:text-purple-400 group-hover:translate-x-1 transition-all"></lucide-icon>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- PHASE 2: ACTIVE SESSION -->
    <div *ngIf="sessionStarted() && !sessionEnded()" class="space-y-6">
      
      <div class="glass-card rounded-2xl p-6 shadow-md border border-white/60 relative overflow-hidden">
        <div class="flex justify-between items-center mb-4">
          <span class="text-xs font-black uppercase tracking-wider text-primary-600 bg-primary-50 border border-primary-100 px-3 py-1 rounded-full">
            Question #{{ questionNumber() }}
          </span>
          <button (click)="handleSpeakQuestion()" class="p-2 bg-primary-50 hover:bg-primary-100 text-primary-600 rounded-xl transition-all flex items-center justify-center btn-interactive" title="Speak Question">
            <lucide-icon [img]="Volume2" [size]="16"></lucide-icon>
          </button>
        </div>
        <h3 class="text-xl font-normal text-gray-800 dark:text-gray-200 leading-snug">{{ currentQuestion() }}</h3>
      </div>

      <div *ngIf="!feedback()" class="glass-card rounded-2xl p-6 shadow-md border border-white/60 relative overflow-hidden">
        
        <div *ngIf="isListening()" class="absolute inset-0 bg-white/95 dark:bg-[#100818]/95 backdrop-blur-sm z-30 flex flex-col items-center justify-center p-6 text-center animate-in fade-in duration-200">
          <div class="relative flex items-center justify-center mb-4">
            <div class="absolute w-20 h-20 bg-coral-100 rounded-full animate-ping opacity-75"></div>
            <div class="w-16 h-16 rounded-full bg-coral-500 text-white flex items-center justify-center shadow-lg relative z-10">
              <lucide-icon [img]="Mic" [size]="28"></lucide-icon>
            </div>
          </div>
          <h4 class="text-lg font-black text-gray-800 dark:text-gray-200">Voice Recording Active</h4>
          <p class="text-xs text-gray-400 mt-1 max-w-xs">Speak clearly into your microphone. Your words will appear in the input field.</p>
          <button (click)="toggleListening()" class="mt-6 px-6 py-3 bg-red-500 hover:bg-red-600 text-white text-xs font-bold uppercase tracking-wider rounded-2xl shadow-md hover:shadow-lg transition-all flex items-center gap-2 hover:scale-102">
            <lucide-icon [img]="MicOff" [size]="14"></lucide-icon> Stop Recording
          </button>
        </div>

        <div class="flex justify-between items-center mb-4">
          <h4 class="font-bold text-gray-800 dark:text-gray-200">Your Answer</h4>
          <button (click)="toggleListening()" [class]="'flex items-center gap-1.5 px-4 py-2 rounded-2xl text-xs font-semibold border transition-all cursor-pointer ' + (isListening() ? 'bg-primary-500 border-primary-500 text-white animate-pulse' : 'bg-white dark:bg-[#100818] dark:text-gray-100 border-primary-200 text-primary-600 hover:bg-primary-50')">
            <lucide-icon [img]="Mic" [size]="14"></lucide-icon> Speak Answer
          </button>
        </div>

        <textarea
          rows="6"
          [ngModel]="userAnswer()"
          (ngModelChange)="userAnswer.set($event)"
          placeholder="Type your response or click 'Speak Answer' to talk..."
          class="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-gray-700 dark:text-gray-300 text-sm mb-4"
          [disabled]="loadingFeedback()"
        ></textarea>

        <div class="flex gap-4">
          <button (click)="handleEndSession()" class="flex-1 py-3.5 bg-gray-100 hover:bg-gray-200 text-gray-600 font-semibold rounded-xl transition-all btn-interactive">
            End Session
          </button>
          <button (click)="handleSubmitAnswer()" [disabled]="loadingFeedback() || !userAnswer().trim()" class="flex-[2] gradient-header text-white font-semibold py-3.5 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive">
            <ng-container *ngIf="loadingFeedback(); else submitTxt">
              <lucide-icon [img]="Loader" class="animate-spin" [size]="18"></lucide-icon> Evaluating...
            </ng-container>
            <ng-template #submitTxt>Submit Answer <lucide-icon [img]="Send" [size]="16"></lucide-icon></ng-template>
          </button>
        </div>
      </div>

      <div *ngIf="feedback()" class="space-y-6">
        <div class="glass-card bg-emerald-50/50 rounded-2xl p-6 shadow-md border border-emerald-100 flex items-center gap-4">
          <div class="w-16 h-16 rounded-full bg-emerald-500 text-white flex flex-col items-center justify-center shadow shrink-0">
            <span class="text-2xl font-black">{{ feedback().score || 0 }}</span>
            <span class="text-[9px] font-semibold text-white/80">/100</span>
          </div>
          <div>
            <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg">Answer Feedback</h4>
            <p class="text-sm text-gray-600 mt-0.5">{{ feedback().suggestion }}</p>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
            <h5 class="font-bold text-emerald-600 mb-3 flex items-center gap-2"><lucide-icon [img]="CheckCircle" [size]="18"></lucide-icon> Strengths</h5>
            <ul class="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
              <li *ngFor="let s of feedback().strengths">{{ s }}</li>
            </ul>
          </div>
          <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
            <h5 class="font-bold text-amber-600 mb-3 flex items-center gap-2"><lucide-icon [img]="AlertTriangle" [size]="18"></lucide-icon> Areas to Improve</h5>
            <ul class="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
              <li *ngFor="let w of feedback().weaknesses">{{ w }}</li>
            </ul>
          </div>
        </div>

        <button (click)="handleNextQuestion()" class="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive">
          Next Question <lucide-icon [img]="ChevronRight" [size]="18"></lucide-icon>
        </button>
      </div>
    </div>

    <!-- PHASE 3: SUMMARY SCREEN (SESSION ENDED) -->
    <div *ngIf="sessionStarted() && sessionEnded()" class="space-y-6">
      <div class="glass-card rounded-2xl p-8 shadow-md border border-white/60 text-center relative overflow-hidden">
        <div class="w-28 h-28 rounded-full gradient-header text-white mx-auto flex flex-col items-center justify-center shadow-lg mb-6">
          <span class="text-4xl font-black">{{ sessionDetails()?.overall_score || 0 }}</span>
          <span class="text-xs font-semibold text-white/80">/100 Overall</span>
        </div>
        <h2 class="text-2xl font-extrabold text-gray-800 dark:text-gray-200 tracking-tight">Interview Finished!</h2>
        <p class="text-gray-500 text-sm max-w-sm mx-auto mt-2 leading-relaxed">Here is how you performed overall during the session.</p>
      </div>

      <div *ngIf="sessionDetails()?.feedback_summary" class="space-y-6">
        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h3 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-2">Overall Feedback</h3>
          <p class="text-sm text-gray-600 leading-relaxed">{{ sessionDetails().feedback_summary.overall_summary }}</p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
            <h4 class="font-bold text-emerald-600 mb-3 flex items-center gap-1.5"><lucide-icon [img]="Award" [size]="18"></lucide-icon> Key Strengths</h4>
            <ul class="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
              <li *ngFor="let s of sessionDetails().feedback_summary.key_strengths">{{ s }}</li>
            </ul>
          </div>
          <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
            <h4 class="font-bold text-amber-600 mb-3 flex items-center gap-1.5"><lucide-icon [img]="AlertTriangle" [size]="18"></lucide-icon> Key Weaknesses</h4>
            <ul class="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
              <li *ngFor="let w of sessionDetails().feedback_summary.key_weaknesses">{{ w }}</li>
            </ul>
          </div>
        </div>

        <div class="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
          <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg mb-3">Action Items</h4>
          <ul class="text-sm text-gray-600 space-y-2">
            <li *ngFor="let item of sessionDetails().feedback_summary.action_items" class="flex gap-2 items-start">
              <span class="text-primary-500 font-bold mt-0.5">•</span><span>{{ item }}</span>
            </li>
          </ul>
        </div>
      </div>

      <div *ngIf="sessionDetails()?.feedback_logs?.length > 0" class="mt-8">
        <h3 class="text-xl font-extrabold text-gray-800 dark:text-gray-200 mb-4 pl-1">Review Answers</h3>
        <div class="space-y-4">
          <div *ngFor="let log of sessionDetails().feedback_logs" class="bg-white dark:bg-[#100818] dark:text-gray-100 rounded-xl p-5 border border-gray-150 shadow-sm space-y-3">
            <div class="flex justify-between items-center">
              <span class="text-xs font-black text-primary-600 uppercase tracking-wide">Question {{ log.question_number }}</span>
              <span class="text-xs font-bold text-emerald-600 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-100">Score: {{ log.confidence_score || 0 }}</span>
            </div>
            <h4 class="font-normal text-gray-800 dark:text-gray-200 text-sm leading-snug">{{ log.question_text }}</h4>
            <div class="bg-gray-50/50 p-3 rounded-2xl border border-gray-100">
              <p class="text-xs text-gray-400 font-bold uppercase tracking-wider mb-1">Your Answer</p>
              <p class="text-sm text-gray-600 italic">"{{ log.user_answer }}"</p>
            </div>
          </div>
        </div>
      </div>

      <button (click)="goBack()" class="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive">
        Back to Dashboard
      </button>
    </div>
  </div>
</div>

// frontend/src/pages/Interview.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import api from '../api/axios';
import { ArrowLeft, Mic, MicOff, Send, CheckCircle, AlertTriangle, Play, Award, Loader, ChevronRight, Volume2, Target } from 'lucide-react';

export default function Interview() {
  const { id } = useParams(); // resume ID
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const sessionIdParam = searchParams.get('session');

  // Fetch Interview History
  const { data: interviewHistory = [] } = useQuery({
    queryKey: ['interviewHistory'],
    queryFn: async () => {
      const res = await api.get('/interview/sessions');
      return res.data;
    }
  });

  // Session state
  const [sessionStarted, setSessionStarted] = useState(false);
  const [sessionEnded, setSessionEnded] = useState(false);
  const [sessionId, setSessionId] = useState(sessionIdParam || null);
  const [sessionType, setSessionType] = useState('behavioral'); // 'behavioral', 'technical', 'pm'
  
  // Q&A round state
  const [questionNumber, setQuestionNumber] = useState(1);
  const [currentQuestion, setCurrentQuestion] = useState('');
  const [userAnswer, setUserAnswer] = useState('');
  
  // Loading states
  const [loadingQuestion, setLoadingQuestion] = useState(false);
  const [loadingFeedback, setLoadingFeedback] = useState(false);
  
  // Feedback log for current question
  const [feedback, setFeedback] = useState(null);
  
  // Entire session history/logs (for review mode)
  const [sessionDetails, setSessionDetails] = useState(null);

  // Web Speech API / Voice state
  const [isListening, setIsListening] = useState(false);
  const recognitionRef = useRef(null);

  // Initialize speech recognition
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      const rec = new SpeechRecognition();
      rec.continuous = true;
      rec.interimResults = true;
      rec.lang = 'en-US';

      rec.onresult = (event) => {
        let interimTranscript = '';
        let finalTranscript = '';

        for (let i = event.resultIndex; i < event.results.length; ++i) {
          if (event.results[i].isFinal) {
            finalTranscript += event.results[i][0].transcript;
          } else {
            interimTranscript += event.results[i][0].transcript;
          }
        }
        setUserAnswer(prev => prev + ' ' + finalTranscript);
      };

      rec.onerror = (e) => {
        console.error('Speech recognition error:', e);
        setIsListening(false);
      };

      rec.onend = () => {
        setIsListening(false);
      };

      recognitionRef.current = rec;
    }
  }, []);

  // Fetch session details if loaded in review mode (from history)
  useEffect(() => {
    if (sessionIdParam) {
      fetchSessionDetails(sessionIdParam);
    }
  }, [sessionIdParam]);

  const fetchSessionDetails = async (sid) => {
    try {
      const res = await api.get(`/interviews/${sid}`);
      setSessionDetails(res.data);
      setSessionEnded(true);
      setSessionStarted(true);
    } catch (e) {
      console.error(e);
    }
  };

  const toggleListening = () => {
    if (!recognitionRef.current) {
      alert('Speech Recognition is not supported in this browser. Try Google Chrome.');
      return;
    }

    if (isListening) {
      recognitionRef.current.stop();
      setIsListening(false);
    } else {
      recognitionRef.current.start();
      setIsListening(true);
    }
  };

  const handleStartSession = async () => {
    setLoadingQuestion(true);
    try {
      const res = await api.post('/interviews/start', {
        resume_id: id,
        session_type: sessionType
      });
      setSessionId(res.data.session_id);
      setCurrentQuestion(res.data.first_question);
      setSessionStarted(true);
      setQuestionNumber(1);
    } catch (e) {
      console.error(e);
      alert('Failed to start interview. Check if database is configured properly.');
    } finally {
      setLoadingQuestion(false);
    }
  };

  const handleSubmitAnswer = async () => {
    if (!userAnswer.trim()) return;
    setLoadingFeedback(true);
    try {
      const res = await api.post(`/interviews/${sessionId}/answer`, {
        question_number: questionNumber,
        question_text: currentQuestion,
        answer: userAnswer
      });
      setFeedback(res.data.feedback);
      
      // We set the next question but don't show it until they click "Next"
      // Store the next question value temporarily
      recognitionRef.current?.stop();
    } catch (e) {
      console.error(e);
      alert('Failed to submit answer.');
    } finally {
      setLoadingFeedback(false);
    }
  };

  const handleNextQuestion = () => {
    if (!feedback) return;
    // Advance to next round
    setCurrentQuestion(feedback.follow_up_question || 'No more questions. Click End Session.');
    setUserAnswer('');
    setFeedback(null);
    setQuestionNumber(prev => prev + 1);
  };

  const handleEndSession = async () => {
    setLoadingQuestion(true);
    try {
      const res = await api.post(`/interviews/${sessionId}/end`);
      // Refresh session details to show the final summary screen
      fetchSessionDetails(sessionId);
    } catch (e) {
      console.error(e);
      alert('Failed to end session.');
    } finally {
      setLoadingQuestion(false);
    }
  };

  // Text-to-speech support for question reading
  const handleSpeakQuestion = () => {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(currentQuestion);
      utterance.rate = 0.95;
      window.speechSynthesis.speak(utterance);
    }
  };

  return (
    <div className="min-h-screen bg-transparent pb-12">
      {/* Header (Static/Unscrollable) */}
      <div className="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
        <div className="w-full flex items-center gap-4">
          <button 
            onClick={() => navigate('/dashboard')} 
            className="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-2xl font-extrabold tracking-tight text-white">AI Mock Coach</h1>
            <p className="text-purple-200 text-sm mt-0.5">Real-time mock interview grounded in your resume</p>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 mt-28">
        
        {/* PHASE 1: START SCREEN */}
        {!sessionStarted && (
          <div className="space-y-6">
            <div className="glass-card rounded-2xl p-8 shadow-md border border-white/60 text-center">
              <div className="w-20 h-20 bg-purple-100 dark:bg-purple-900/40 text-purple-600 dark:text-purple-400 rounded-xl mx-auto flex items-center justify-center mb-6 shadow-sm">
                <Play size={36} className="fill-current" />
              </div>
              
              <h2 className="text-2xl font-extrabold text-gray-800 dark:text-gray-200 tracking-tight">Ready to Prep?</h2>
              <p className="text-gray-500 text-sm max-w-sm mx-auto mt-2 leading-relaxed">
                We'll generate customized questions targeting the experience and projects on your resume.
              </p>

              <div className="mt-8 max-w-xs mx-auto space-y-4">
                <div className="text-left">
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-wider block mb-2 pl-2">
                    Choose session type
                  </label>
                  <div className="flex bg-gray-100/50 p-1 rounded-2xl border border-gray-100">
                    {['behavioral', 'technical', 'pm'].map((type) => (
                      <button
                        key={type}
                        onClick={() => setSessionType(type)}
                        className={`flex-1 py-2 text-xs font-bold rounded-xl uppercase transition-all cursor-pointer ${
                          sessionType === type 
                            ? 'bg-white dark:bg-[#100818] dark:text-gray-100 text-purple-600 dark:text-purple-400 shadow-sm' 
                            : 'text-gray-400 hover:text-gray-500'
                        }`}
                      >
                        {type}
                      </button>
                    ))}
                  </div>
                </div>

                <button
                  onClick={handleStartSession}
                  disabled={loadingQuestion}
                  className="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive cursor-pointer"
                >
                  {loadingQuestion ? 'Generating first question...' : 'Start Interview'}
                </button>
              </div>
            </div>

            {/* Past Session History list */}
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-white tracking-tight pl-1">Past Sessions History</h3>
              <div className="space-y-3">
                {interviewHistory.length === 0 ? (
                  <div className="bg-white/5 border border-dashed border-white/10 rounded-2xl p-8 text-center text-white/60 text-sm">
                    No mock sessions completed yet.
                  </div>
                ) : (
                  interviewHistory.map((session) => (
                    <div 
                      key={session.id}
                      onClick={() => {
                        navigate(`/interview/${session.resume_id}?session=${session.id}`);
                        window.location.reload();
                      }}
                      className="glass-card rounded-xl p-4 shadow-sm hover:shadow-lg transition-all border border-white/40 flex items-center justify-between cursor-pointer group"
                    >
                      <div className="flex items-center gap-3 min-w-0">
                        <div className="p-3 bg-purple-50 dark:bg-purple-900/20 text-purple-650 rounded-2xl shrink-0">
                          <Target size={18} />
                        </div>
                        <div className="min-w-0">
                          <h4 className="font-bold text-slate-800 dark:text-slate-200 group-hover:text-purple-600 dark:text-purple-400 transition-colors capitalize truncate max-w-[180px] sm:max-w-[240px]">
                            {session.session_type} Prep
                          </h4>
                          <p className="text-slate-400 text-[10px] mt-0.5">
                            {new Date(session.started_at).toLocaleDateString()} • {session.question_count} Qs
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        <span className="font-black text-slate-700 bg-slate-100 px-2.5 py-0.5 rounded-full text-[10px]">
                          {session.overall_score || 0}%
                        </span>
                        <ChevronRight size={14} className="text-slate-400 group-hover:text-purple-600 dark:text-purple-400 group-hover:translate-x-1 transition-all" />
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        )}

        {/* PHASE 2: ACTIVE SESSION */}
        {sessionStarted && !sessionEnded && (
          <div className="space-y-6">
            
            {/* Question Card */}
            <div className="glass-card rounded-2xl p-6 shadow-md border border-white/60 relative overflow-hidden">
              <div className="flex justify-between items-center mb-4">
                <span className="text-xs font-black uppercase tracking-wider text-primary-600 bg-primary-50 border border-primary-100 px-3 py-1 rounded-full">
                  Question #{questionNumber}
                </span>
                <button
                  onClick={handleSpeakQuestion}
                  className="p-2 bg-primary-50 hover:bg-primary-100 text-primary-600 rounded-xl transition-all flex items-center justify-center btn-interactive"
                  title="Speak Question"
                >
                  <Volume2 size={16} />
                </button>
              </div>

              <h3 className="text-xl font-extrabold text-gray-800 dark:text-gray-200 leading-snug">
                {currentQuestion}
              </h3>
            </div>

            {!feedback ? (
              <div className="glass-card rounded-2xl p-6 shadow-md border border-white/60 relative overflow-hidden">
                {/* Speech Recognition Active Overlay Popup */}
                {isListening && (
                  <div className="absolute inset-0 bg-white/95 dark:bg-[#100818]/95 backdrop-blur-sm z-30 flex flex-col items-center justify-center p-6 text-center animate-in fade-in duration-200">
                    <div className="relative flex items-center justify-center mb-4">
                      <div className="absolute w-20 h-20 bg-coral-100 rounded-full animate-ping opacity-75"></div>
                      <div className="w-16 h-16 rounded-full bg-coral-500 text-white flex items-center justify-center shadow-lg relative z-10">
                        <Mic size={28} />
                      </div>
                    </div>
                    <h4 className="text-lg font-black text-gray-800 dark:text-gray-200">Voice Recording Active</h4>
                    <p className="text-xs text-gray-400 mt-1 max-w-xs">
                      Speak clearly into your microphone. Your words will appear in the input field.
                    </p>
                    
                    <button
                      onClick={toggleListening}
                      className="mt-6 px-6 py-3 bg-red-500 hover:bg-red-600 text-white text-xs font-bold uppercase tracking-wider rounded-2xl shadow-md hover:shadow-lg transition-all flex items-center gap-2 hover:scale-102"
                    >
                      <MicOff size={14} /> Stop Recording
                    </button>
                  </div>
                )}

                <div className="flex justify-between items-center mb-4">
                  <h4 className="font-bold text-gray-800 dark:text-gray-200">Your Answer</h4>
                  {/* Voice Button */}
                  <button
                    onClick={toggleListening}
                    className={`flex items-center gap-1.5 px-4 py-2 rounded-2xl text-xs font-semibold border transition-all cursor-pointer ${
                      isListening 
                        ? 'bg-primary-500 border-primary-500 text-white animate-pulse' 
                        : 'bg-white dark:bg-[#100818] dark:text-gray-100 border-primary-200 text-primary-600 hover:bg-primary-50'
                    }`}
                  >
                    <Mic size={14} /> Speak Answer
                  </button>
                </div>

                <textarea
                  rows={6}
                  value={userAnswer}
                  onChange={(e) => setUserAnswer(e.target.value)}
                  placeholder="Type your response or click 'Speak Answer' to talk..."
                  className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-gray-700 dark:text-gray-300 text-sm mb-4"
                  disabled={loadingFeedback}
                />

                <div className="flex gap-4">
                  <button
                    onClick={handleEndSession}
                    className="flex-1 py-3.5 bg-gray-100 hover:bg-gray-200 text-gray-600 font-semibold rounded-xl transition-all btn-interactive"
                  >
                    End Session
                  </button>
                  <button
                    onClick={handleSubmitAnswer}
                    disabled={loadingFeedback || !userAnswer.trim()}
                    className="flex-[2] gradient-header text-white font-semibold py-3.5 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive"
                  >
                    {loadingFeedback ? (
                      <>
                        <Loader className="animate-spin" size={18} /> Evaluating...
                      </>
                    ) : (
                      <>
                        Submit Answer <Send size={16} />
                      </>
                    )}
                  </button>
                </div>
              </div>
            ) : (
              /* Feedback Display Card */
              <div className="space-y-6">
                <div className="glass-card bg-emerald-50/50 rounded-2xl p-6 shadow-md border border-emerald-100 flex items-center gap-4">
                  <div className="w-16 h-16 rounded-full bg-emerald-500 text-white flex flex-col items-center justify-center shadow shrink-0">
                    <span className="text-2xl font-black">{feedback.score || 0}</span>
                    <span className="text-[9px] font-semibold text-white/80">/100</span>
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg">Answer Feedback</h4>
                    <p className="text-sm text-gray-600 mt-0.5">{feedback.suggestion}</p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                    <h5 className="font-bold text-emerald-600 mb-3 flex items-center gap-2">
                      <CheckCircle size={18} /> Strengths
                    </h5>
                    <ul className="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
                      {feedback.strengths?.map((s, i) => <li key={i}>{s}</li>)}
                    </ul>
                  </div>

                  <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                    <h5 className="font-bold text-amber-600 mb-3 flex items-center gap-2">
                      <AlertTriangle size={18} /> Areas to Improve
                    </h5>
                    <ul className="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
                      {feedback.weaknesses?.map((w, i) => <li key={i}>{w}</li>)}
                    </ul>
                  </div>
                </div>

                <button
                  onClick={handleNextQuestion}
                  className="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive"
                >
                  Next Question <ChevronRight size={18} />
                </button>
              </div>
            )}
          </div>
        )}

        {/* PHASE 3: SUMMARY SCREEN (SESSION ENDED) */}
        {sessionStarted && sessionEnded && (
          <div className="space-y-6">
            
            {/* Overview Score Card */}
            <div className="glass-card rounded-2xl p-8 shadow-md border border-white/60 text-center relative overflow-hidden">
              <div className="w-28 h-28 rounded-full gradient-header text-white mx-auto flex flex-col items-center justify-center shadow-lg mb-6">
                <span className="text-4xl font-black">{sessionDetails?.overall_score || 0}</span>
                <span className="text-xs font-semibold text-white/80">/100 Overall</span>
              </div>

              <h2 className="text-2xl font-extrabold text-gray-800 dark:text-gray-200 tracking-tight">Interview Finished!</h2>
              <p className="text-gray-500 text-sm max-w-sm mx-auto mt-2 leading-relaxed">
                Here is how you performed overall during the session.
              </p>
            </div>

            {/* AI Summary details */}
            {sessionDetails?.feedback_summary && (
              <div className="space-y-6">
                <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h3 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-2">Overall Feedback</h3>
                  <p className="text-sm text-gray-600 leading-relaxed">
                    {sessionDetails.feedback_summary.overall_summary}
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                    <h4 className="font-bold text-emerald-600 mb-3 flex items-center gap-1.5">
                      <Award size={18} /> Key Strengths
                    </h4>
                    <ul className="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
                      {sessionDetails.feedback_summary.key_strengths?.map((s, i) => <li key={i}>{s}</li>)}
                    </ul>
                  </div>

                  <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                    <h4 className="font-bold text-amber-600 mb-3 flex items-center gap-1.5">
                      <AlertTriangle size={18} /> Key Weaknesses
                    </h4>
                    <ul className="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
                      {sessionDetails.feedback_summary.key_weaknesses?.map((w, i) => <li key={i}>{w}</li>)}
                    </ul>
                  </div>
                </div>

                 <div className="glass-card rounded-2xl p-6 shadow-sm border border-white/60">
                  <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg mb-3">Action Items</h4>
                  <ul className="text-sm text-gray-600 space-y-2">
                    {sessionDetails.feedback_summary.action_items?.map((item, i) => (
                      <li key={i} className="flex gap-2 items-start">
                        <span className="text-primary-500 font-bold mt-0.5">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}

            {/* Q&A logs review */}
            {sessionDetails?.feedback_logs?.length > 0 && (
              <div className="mt-8">
                <h3 className="text-xl font-extrabold text-gray-800 dark:text-gray-200 mb-4 pl-1">Review Answers</h3>
                <div className="space-y-4">
                  {sessionDetails.feedback_logs.map((log) => (
                    <div key={log.id} className="bg-white dark:bg-[#100818] dark:text-gray-100 rounded-xl p-5 border border-gray-150 shadow-sm space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-xs font-black text-primary-600 uppercase tracking-wide">
                          Question {log.question_number}
                        </span>
                        <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-100">
                          Score: {log.confidence_score || 0}
                        </span>
                      </div>
                      <h4 className="font-bold text-gray-800 dark:text-gray-200 text-sm leading-snug">{log.question_text}</h4>
                      <div className="bg-gray-50/50 p-3 rounded-2xl border border-gray-100">
                        <p className="text-xs text-gray-400 font-bold uppercase tracking-wider mb-1">Your Answer</p>
                        <p className="text-sm text-gray-600 italic">"{log.user_answer}"</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <button
              onClick={() => navigate('/dashboard')}
              className="w-full gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 btn-interactive"
            >
              Back to Dashboard
            </button>
          </div>
        )}

      </div>
    </div>
  );
}
