// frontend/src/app/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { LucideAngularModule, Mail, Lock, FileText, ArrowRight } from 'lucide-angular';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, LucideAngularModule],
  templateUrl: './login.component.html',
  styles: ``
})
export class LoginComponent {
  email = '';
  password = '';
  error = '';
  loading = false;

  readonly Mail = Mail;
  readonly Lock = Lock;
  readonly FileText = FileText;
  readonly ArrowRight = ArrowRight;

  private authService = inject(AuthService);

  onSubmit() {
    this.error = '';
    this.loading = true;
    this.authService.login({ email: this.email, password: this.password }).subscribe({
      next: () => {
        this.loading = false;
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to login';
        this.loading = false;
      }
    });
  }
}

<div class="min-h-screen bg-transparent flex items-center justify-center p-4">
  <div class="w-full max-w-md bg-white/40 backdrop-blur-md rounded-5xl shadow-2xl p-8 border border-white/40">
    <div class="flex flex-col items-center mb-8">
      <div class="w-16 h-16 gradient-header rounded-xl flex items-center justify-center text-white shadow-md mb-4">
        <lucide-icon [img]="FileText" [size]="32"></lucide-icon>
      </div>
      <h2 class="text-3xl font-extrabold text-slate-800 dark:text-slate-200 tracking-tight">ResumeFlow</h2>
      <p class="text-slate-550 text-sm mt-1 font-medium">AI-Powered Resume Analyzer</p>
    </div>

    <div *ngIf="error" class="mb-6 p-4 bg-red-50/90 backdrop-blur-sm border border-red-100 text-red-650 text-sm rounded-2xl text-center font-bold shadow-sm">
      {{ error }}
    </div>

    <form (ngSubmit)="onSubmit()" class="space-y-5">
      <div class="relative">
        <lucide-icon [img]="Mail" class="absolute left-4 top-3.5 text-purple-400" [size]="20"></lucide-icon>
        <input
          type="email"
          placeholder="Email address"
          [(ngModel)]="email"
          name="email"
          class="w-full pl-12 pr-4 py-3.5 bg-white/95 dark:bg-[#100818]/95 border border-purple-100/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-slate-800 dark:text-slate-200 font-medium shadow-sm"
          required
        />
      </div>

      <div class="relative">
        <lucide-icon [img]="Lock" class="absolute left-4 top-3.5 text-purple-400" [size]="20"></lucide-icon>
        <input
          type="password"
          placeholder="Password"
          [(ngModel)]="password"
          name="password"
          class="w-full pl-12 pr-4 py-3.5 bg-white/95 dark:bg-[#100818]/95 border border-purple-100/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-slate-800 dark:text-slate-200 font-medium shadow-sm"
          required
        />
      </div>

      <button
        type="submit"
        [disabled]="loading"
        class="w-full gradient-header text-white font-bold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive cursor-pointer"
      >
        {{ loading ? 'Logging in...' : 'Log In' }}
        <lucide-icon [img]="ArrowRight" [size]="18"></lucide-icon>
      </button>
    </form>

    <div class="mt-8 text-center text-sm text-slate-500 dark:text-slate-400 font-medium">
      Don't have an account? 
      <a routerLink="/register" class="text-purple-600 dark:text-purple-400 font-extrabold hover:underline">
        Register here
      </a>
    </div>
  </div>
</div>

// frontend/src/pages/Login.jsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import api from '../api/axios';
import useAuthStore from '../store/useAuthStore';
import { Mail, Lock, User, FileText, ArrowRight } from 'lucide-react';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuthStore();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await api.post('/auth/login', { email, password });
      login(res.data.user, res.data.token);
      navigate('/dashboard');
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to login');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-transparent flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-white/40 backdrop-blur-md rounded-5xl shadow-2xl p-8 border border-white/40">
        <div className="flex flex-col items-center mb-8">
          <div className="w-16 h-16 gradient-header rounded-xl flex items-center justify-center text-white shadow-md mb-4">
            <FileText size={32} />
          </div>
          <h2 className="text-3xl font-extrabold text-slate-800 dark:text-slate-200 tracking-tight">ResumeFlow</h2>
          <p className="text-slate-550 text-sm mt-1 font-medium">AI-Powered Resume Analyzer</p>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-50/90 backdrop-blur-sm border border-red-100 text-red-650 text-sm rounded-2xl text-center font-bold shadow-sm">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5">
          <div className="relative">
            <Mail className="absolute left-4 top-3.5 text-purple-400" size={20} />
            <input
              type="email"
              placeholder="Email address"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full pl-12 pr-4 py-3.5 bg-white/95 dark:bg-[#100818]/95 border border-purple-100/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-slate-800 dark:text-slate-200 font-medium shadow-sm"
              required
            />
          </div>

          <div className="relative">
            <Lock className="absolute left-4 top-3.5 text-purple-400" size={20} />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full pl-12 pr-4 py-3.5 bg-white/95 dark:bg-[#100818]/95 border border-purple-100/60 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400 focus:bg-white dark:bg-[#100818] dark:text-gray-100 transition-all text-slate-800 dark:text-slate-200 font-medium shadow-sm"
              required
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full gradient-header text-white font-bold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive cursor-pointer"
          >
            {loading ? 'Logging in...' : 'Log In'}
            <ArrowRight size={18} />
          </button>
        </form>

        <div className="mt-8 text-center text-sm text-slate-500 dark:text-slate-400 font-medium">
          Don't have an account?{' '}
          <Link to="/register" className="text-purple-600 dark:text-purple-400 font-extrabold hover:underline">
            Register here
          </Link>
        </div>
      </div>
    </div>
  );
}
