// frontend/src/app/pages/upload/upload.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { LucideAngularModule, ArrowLeft, Upload, FileText, Loader } from 'lucide-angular';

@Component({
  selector: 'app-upload',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './upload.component.html',
  styles: ``
})
export class UploadComponent {
  private router = inject(Router);
  private http = inject(HttpClient);

  ArrowLeft = ArrowLeft; Upload = Upload; FileText = FileText; Loader = Loader;

  file = signal<File | null>(null);
  dragging = signal(false);
  loading = signal(false);
  error = signal('');

  handleDragOver(e: DragEvent) {
    e.preventDefault();
    this.dragging.set(true);
  }

  handleDragLeave(e: DragEvent) {
    this.dragging.set(false);
  }

  handleDrop(e: DragEvent) {
    e.preventDefault();
    this.dragging.set(false);
    const droppedFile = e.dataTransfer?.files[0];
    if (droppedFile && droppedFile.type === 'application/pdf') {
      this.file.set(droppedFile);
      this.error.set('');
    } else {
      this.error.set('Please upload a valid PDF file.');
    }
  }

  handleFileChange(event: Event) {
    const selectedFile = (event.target as HTMLInputElement).files?.[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      this.file.set(selectedFile);
      this.error.set('');
    } else {
      this.error.set('Please upload a valid PDF file.');
    }
  }

  clearFile() {
    this.file.set(null);
  }

  handleUpload() {
    const currentFile = this.file();
    if (!currentFile) return;

    this.loading.set(true);
    this.error.set('');
    
    const formData = new FormData();
    formData.append('file', currentFile);

    this.http.post<any>('http://localhost:8081/api/v1/resumes/upload', formData).subscribe({
      next: (res) => {
        this.router.navigate([`/analysis/${res.resume_id}`]);
      },
      error: (err) => {
        console.error(err);
        this.error.set(err.error?.error || 'Failed to upload and parse resume. Please make sure the Affinda API key is valid.');
        this.loading.set(false);
      }
    });
  }

  goBack() {
    this.router.navigate(['/dashboard']);
  }
}

<div class="min-h-screen bg-transparent pb-12">
  <div class="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
    <div class="w-full flex items-center gap-4">
      <button 
        (click)="goBack()" 
        class="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
      >
        <lucide-icon [img]="ArrowLeft" [size]="20"></lucide-icon>
      </button>
      <div>
        <h1 class="text-2xl font-extrabold tracking-tight text-white">Upload Resume</h1>
        <p class="text-purple-200 text-sm mt-0.5">We support PDF files up to 10MB</p>
      </div>
    </div>
  </div>

  <div class="max-w-xl mx-auto px-4 mt-28">
    <div class="glass-card rounded-2xl p-8 shadow-md border border-white/60">
      
      <div
        (dragover)="handleDragOver($event)"
        (dragleave)="handleDragLeave($event)"
        (drop)="handleDrop($event)"
        [class]="'border-2 border-dashed rounded-xl p-10 flex flex-col items-center justify-center transition-all ' + 
          (dragging() ? 'border-primary-400 bg-primary-50/50' : 
            (file() ? 'border-emerald-300 bg-emerald-50/10' : 'border-primary-200 hover:border-primary-300 bg-gray-50/30'))"
      >
        <input
          type="file"
          id="resume-file"
          accept=".pdf"
          class="hidden"
          (change)="handleFileChange($event)"
          [disabled]="loading()"
        />
        
        <div *ngIf="file(); else emptyState" class="flex flex-col items-center">
          <div class="p-4 bg-emerald-100 text-emerald-500 rounded-xl mb-4">
            <lucide-icon [img]="FileText" [size]="40"></lucide-icon>
          </div>
          <h4 class="font-bold text-gray-800 dark:text-gray-200 text-lg text-center max-w-[280px] truncate">{{ file()?.name }}</h4>
          <p class="text-gray-400 text-sm mt-1">{{ (file()!.size / 1024 / 1024).toFixed(2) }} MB</p>
          
          <button
            (click)="clearFile()"
            class="mt-4 text-xs font-semibold text-primary-500 hover:underline"
            [disabled]="loading()"
          >
            Change File
          </button>
        </div>
        
        <ng-template #emptyState>
          <label for="resume-file" class="cursor-pointer flex flex-col items-center w-full">
            <div class="p-4 bg-primary-100 text-primary-500 rounded-xl mb-4 transition-transform hover:scale-105">
              <lucide-icon [img]="Upload" [size]="40"></lucide-icon>
            </div>
            <h4 class="font-bold text-gray-700 dark:text-gray-300 text-lg">Drag & Drop Resume</h4>
            <p class="text-gray-400 text-sm mt-1">or click to browse from files</p>
          </label>
        </ng-template>
      </div>

      <div *ngIf="error()" class="mt-6 p-4 bg-red-50 border border-red-100 text-red-600 text-sm rounded-2xl text-center font-semibold">
        {{ error() }}
      </div>

      <button
        *ngIf="file()"
        (click)="handleUpload()"
        [disabled]="loading()"
        class="w-full mt-6 gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive"
      >
        <ng-container *ngIf="loading(); else btnText">
          <lucide-icon [img]="Loader" class="animate-spin" [size]="18"></lucide-icon>
          Parsing resume structure with AI...
        </ng-container>
        <ng-template #btnText>
          Process Resume
        </ng-template>
      </button>

    </div>
  </div>
</div>

// frontend/src/pages/Upload.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
import { Upload as UploadIcon, FileText, ArrowLeft, Loader } from 'lucide-react';

export default function Upload() {
  const [file, setFile] = useState(null);
  const [dragging, setDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleDragOver = (e) => {
    e.preventDefault();
    setDragging(true);
  };

  const handleDragLeave = () => {
    setDragging(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragging(false);
    const droppedFile = e.dataTransfer.files[0];
    if (droppedFile && droppedFile.type === 'application/pdf') {
      setFile(droppedFile);
      setError('');
    } else {
      setError('Please upload a valid PDF file.');
    }
  };

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setError('');
    } else {
      setError('Please upload a valid PDF file.');
    }
  };

  const handleUpload = async () => {
    if (!file) return;
    setLoading(true);
    setError('');
    
    const formData = new FormData();
    formData.append('file', file);

    try {
      const res = await api.post('/resumes/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      // Navigate to analysis page of newly created resume
      navigate(`/analysis/${res.data.resume_id}`);
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.error || 'Failed to upload and parse resume. Please make sure the Affinda API key is valid.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-transparent pb-12">
      {/* Header (Static/Unscrollable) */}
      <div className="fixed top-0 left-0 right-0 z-50 frosted-header rounded-b-[36px] px-8 py-5 shadow-sm">
        <div className="w-full flex items-center gap-4">
          <button 
            onClick={() => navigate('/dashboard')} 
            className="p-3 bg-white dark:bg-[#100818] dark:text-gray-100 hover:bg-violet-50 border border-violet-100 rounded-2xl transition-all text-violet-600 flex items-center justify-center btn-interactive shadow-sm"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-2xl font-extrabold tracking-tight text-white">Upload Resume</h1>
            <p className="text-purple-200 text-sm mt-0.5">We support PDF files up to 10MB</p>
          </div>
        </div>
      </div>

      <div className="max-w-xl mx-auto px-4 mt-28">
        <div className="glass-card rounded-2xl p-8 shadow-md border border-white/60">
          
          {/* Drag & Drop Area */}
          <div
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={`border-2 border-dashed rounded-xl p-10 flex flex-col items-center justify-center transition-all ${
              dragging 
                ? 'border-primary-400 bg-primary-50/50' 
                : file 
                  ? 'border-emerald-300 bg-emerald-50/10' 
                  : 'border-primary-200 hover:border-primary-300 bg-gray-50/30'
            }`}
          >
            <input
              type="file"
              id="resume-file"
              accept=".pdf"
              className="hidden"
              onChange={handleFileChange}
              disabled={loading}
            />
            
            {file ? (
              <div className="flex flex-col items-center">
                <div className="p-4 bg-emerald-100 text-emerald-500 rounded-xl mb-4">
                  <FileText size={40} />
                </div>
                <h4 className="font-bold text-gray-800 dark:text-gray-200 text-lg text-center max-w-[280px] truncate">{file.name}</h4>
                <p className="text-gray-400 text-sm mt-1">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                
                <button
                  onClick={() => setFile(null)}
                  className="mt-4 text-xs font-semibold text-primary-500 hover:underline"
                  disabled={loading}
                >
                  Change File
                </button>
              </div>
            ) : (
              <label htmlFor="resume-file" className="cursor-pointer flex flex-col items-center w-full">
                <div className="p-4 bg-primary-100 text-primary-500 rounded-xl mb-4 transition-transform hover:scale-105">
                  <UploadIcon size={40} />
                </div>
                <h4 className="font-bold text-gray-700 dark:text-gray-300 text-lg">Drag & Drop Resume</h4>
                <p className="text-gray-400 text-sm mt-1">or click to browse from files</p>
              </label>
            )}
          </div>

          {error && (
            <div className="mt-6 p-4 bg-red-50 border border-red-100 text-red-600 text-sm rounded-2xl text-center font-semibold animate-shake">
              {error}
            </div>
          )}

          {/* Action Button */}
          {file && (
            <button
              onClick={handleUpload}
              disabled={loading}
              className="w-full mt-6 gradient-header text-white font-semibold py-4 rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2 hover:opacity-90 disabled:opacity-50 btn-interactive"
            >
              {loading ? (
                <>
                  <Loader className="animate-spin" size={18} />
                  Parsing resume structure with AI...
                </>
              ) : (
                'Process Resume'
              )}
            </button>
          )}

        </div>
      </div>
    </div>
  );
}
